### ISSUE TITLE
RuntimeError: Session is closed

### ISSUE THREAD

**Issue by ddmrtc** [daxartio/tinvest#18]
не обрабатывается закрытие коннекта сервером

websocket connection is closing.
```
Traceback (most recent call last):
  File "streaming_to_db.py", line 95, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "streaming_to_db.py", line 79, in main
    await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinvest\streaming.py", line 35, in wrapper
    await func(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinvest\streaming.py", line 85, in run
    async with self._session.ws_connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 721, in _ws_connect
    resp = await self.request(method, url,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```

лучше чем поставить в while await tinvest.Streaming придумать не смог, заново обрабатывается @events.startup() и exception выше показывается.
Как можно сделать обработку переподключения? например как сделано в 
https://github.com/daxartio/tinvest/blob/a12757e8bb74e4008e80f872eea6290473ad720a/tinvest/streaming.py#L100 ?

**Comment by daxartio** [comment]
Я понял. Добавлю хендлер на это. Будет 
```python
events = tinvest.StreamingEvents()

@events.reconnect()
def handle_reconnect():
    pass
```

Пока можно использовать флаг. Просто если повторно вызывается startup, то значит произошел reconnect

**Comment by ddmrtc** [comment]
Не, ошибся, while не помогает, срабатывает try..except..finally который в примере есть в __main__, т.е. реконнект даже не пытается делать, я пытался как то обработать исключение RuntimeError в async def run(self), но у меня не вышло

вот здесь описано что такое бывает, если открывать с использованием async with
https://github.com/aaugustin/websockets/issues/367
но моих знаний не хватает что бы это понять(

**Comment by daxartio** [comment]
Тут я не могу контролировать такие ошибки, надо пытаться повторить переподключение и без повторного вызова @Events.startup() не обойтись

**Comment by ddmrtc** [comment]
вот такая обработка нормально работает

async def main():
    while True:
        try:
            await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
        except RuntimeError as e:
            pass
        finally:
            pass
