### ISSUE TITLE
Streaming 423 message='Invalid response status'

### ISSUE THREAD

**Issue by ddmrtc** [daxartio/tinvest#19]
Исключение, если открыть больше 6 соединений до streaming api сейчас выглядит вот так

```
Traceback (most recent call last):
  File "streaming_to_db.py", line 95, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "streaming_to_db.py", line 79, in main
    await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinvest\streaming.py", line 35, in wrapper
    await func(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinvest\streaming.py", line 85, in run
    async with self._session.ws_connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 733, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 423, message='Invalid response status', url=URL('wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x099B0BE0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x099BEC58>, 177902.421)]']
connector: <aiohttp.connector.TCPConnector object at 0x099B0B68>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x099B0E20>
transport: <_ProactorSocketTransport fd=2488 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x02EC45C8>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 322, in __del__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 317, in close
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 594, in _start_shutdown
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 599, in _write_appdata
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 707, in _process_write_backlog
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 721, in _fatal_error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
```
Возможно тоже написать обработчик

**Comment by daxartio** [comment]
Такие ошибки стоит обрабатывать на своей стороне. Тут я не могу в это лезть.

**Comment by recoshet** [comment]
@ddmrtc в доках сказано, что не больше 6 соединений на клиента. А вот в пределах одного соединения можно подписаться на множество событий (больше 6)

**Comment by recoshet** [comment]
@daxartio подскажи, как реализовать подписку отписку в процессе по внешнему событию. Не получается вернуть управление стартовой функции.

Попробовал что то такое:
```
@events.startup()
async def startup(api: tinvest.StreamingApi):
    figiList = ['BBG000QJW156','BBG004730JJ5','BBG004730ZJ9','BBG006L8G4H1','BBG000K3STR7','BBG004S68758','BBG004731354','BBG0013HGFT4']
    while True:
        if len(figiList) > 0:
            await api.candle.subscribe(figiList[0], "1min")
            print('subscribe '+figiList[0])
            figiList = figiList[1:]
        await asyncio.sleep(1)
```
Хотел после await asyncio.sleep(1) реализовать опрос, например из файла, и добавлять удалять подписки не останавливая скрипт. Но естественно тут всё зависает и цикл while true не отпускает. Python пока плохо знаю.

**Comment by ddmrtc** [comment]
> @ddmrtc в доках сказано, что не больше 6 соединений на клиента. А вот в пределах одного соединения можно подписаться на множество событий (больше 6)

я в курсе, спасибо)

**Comment by daxartio** [comment]
> Хотел после await asyncio.sleep(1) реализовать опрос, например из файла, и добавлять удалять подписки не останавливая скрипт. Но естественно тут всё зависает и цикл while true не отпускает.

@recoshet тебе надо создать в отдельной таске

например так:

```python

@events.startup()
async def startup(api: tinvest.StreamingApi):
    api['tasks'].append(asyncio.create_task(my_subscriber(api)))


@events.cleanup()
async def cleanup(api: tinvest.StreamingApi):
    await api['tasks'][0]


async def my_subscriber(api: tinvest.StreamingApi):
    figiList = ['BBG000QJW156','BBG004730JJ5','BBG004730ZJ9','BBG006L8G4H1','BBG000K3STR7','BBG004S68758','BBG004731354','BBG0013HGFT4']
    while True:
        if len(figiList) > 0:
            await api.candle.subscribe(figiList[0], "1min")
            print('subscribe '+figiList[0])
            figiList = figiList[1:]
        await asyncio.sleep(1)


async def main():
    await tinvest.Streaming(TOKEN, state={"tasks": []}).add_handlers(events).run()
```
Не стоит забывать, что таску надо авэйтнуть при закрытии

**Comment by recoshet** [comment]
@daxartio большое спасибо! Работает как надо) Очень благодарен!
