### ISSUE TITLE
ValueError: Invalid isoformat string: '2020-04-16T16:51:10.82311Z'

### ISSUE THREAD

**Issue by ddmrtc** [daxartio/tinvest#20]
Иногда возникает проблема с датой, можно поправить на 
server_time = datetime.fromisoformat(data['time'][:23])
```
Traceback (most recent call last):
  File "stream.py", line 976, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "stream.py", line 957, in main
    await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 36, in wrapper
    await func(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 97, in run
    await self._run(ws)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 119, in _run
    server_time = datetime.fromisoformat(data['time'][:26])
ValueError: Invalid isoformat string: '2020-04-16T16:51:10.82311Z'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000222B3A5CCD0>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000222AF5CF160>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
```
Process returned 1 (0x1)        execution time : 3055.285 s

**Comment by daxartio** [comment]
Через час выкачу исправление, миллисекунды сохранятся

**Comment by ddmrtc** [comment]
ок, fyi c 23 тоже не сработало, хотя если отдельно проверять работает:
from datetime import datetime
date = '2020-04-16T17:43:58.27327Z'
server_time = datetime.fromisoformat(date[:23])
print(server_time)


Traceback (most recent call last):
  File "stream.py", line 976, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "stream.py", line 957, in main
    await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 36, in wrapper
    await func(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 97, in run
    await self._run(ws)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\tinvest\streaming.py", line 119, in _run
    server_time = datetime.fromisoformat(data['time'][:23])
ValueError: Invalid isoformat string: '2020-04-16T17:43:58.27327Z'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014FF24CC5B0>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014FEE04E160>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
